version: '3.8'

services:

  mysql:
    image: mysql:8.0.25
    container_name: mysql
    ports: 
        - 3306:3306
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root